In [1]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

from random import shuffle
from sklearn.utils import shuffle


In [3]:
TRAIN_PATH='/content/drive/MyDrive/UIT/HocKy8/KLTN/detect_attack_by_reinforcement_learning/data/matrix1/normal/train-normal.csv'

In [4]:
df = pd.read_csv(TRAIN_PATH)
dataset = df.to_numpy()

In [5]:

# Define the dataset (assuming it's a numpy array)
# dataset = np.array([...])  # Replace [...] with your dataset

# Define the parameters
n = 32  # Number of consecutive samples in each mini-batch

# Randomly permute the dataset
np.random.shuffle(dataset)

# Generate a mini-batch
def generate_mini_batch(dataset, n):
    # Choose a random starting index
    start_index = np.random.randint(0, len(dataset) - n - 1)
    
    # Select n+1 consecutive samples starting from the random index
    mini_batch = dataset[start_index : start_index + n + 1]
    
    return mini_batch

# Generate a mini-batch using the defined structure
mini_batch = generate_mini_batch(dataset, n)

# Print the mini-batch
print(mini_batch)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
